Apply feedback from sthen@:
- USE_LIBTOOL=Yes and add libltdl LIB_DEPENDS.  Note that for this to
  work I had to tell CONFIGURE_ENV to set a funky -D define in CFLAGS;
  otherwise we will get an "undefined reference to
  `lt__PROGRAM__LTX_preloaded_symbols'" error with libtool/libltdl 2.4.
  I am not sure if this is the right way to do it.

- Do not pack *.a files (the *.la files are still packed since they are
  required by the port)