angr: cle: Remove unneeded/breaking patch
This patches causes

	$ python3
	>>> import angr
	>>> p = angr.Project('/bin/ls')
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	  File "/usr/local/lib/python3.7/site-packages/angr/project.py", line 121, in __init__
	    self.loader = cle.Loader(self.filename, concrete_target=concrete_target, **load_options)
	  File "/usr/local/lib/python3.7/site-packages/cle/loader.py", line 128, in __init__
	    self.initial_load_objects = self._internal_load(main_binary, *preload_libs, preloading=True)
	  File "/usr/local/lib/python3.7/site-packages/cle/loader.py", line 645, in _internal_load
	  main_obj = self._load_object_isolated(main_spec)
	  File "/usr/local/lib/python3.7/site-packages/cle/loader.py", line 748, in _load_object_isolated
	  return backend_cls(full_spec, is_main_bin=self.main_object is None, loader=self, **options)
	  File "/usr/local/lib/python3.7/site-packages/cle/backends/elf/elf.py", line 112, in __init__
	    self.__register_segments()
	  File "/usr/local/lib/python3.7/site-packages/cle/backends/elf/elf.py", line 499, in __register_segments
	    self.__register_dyn(seg)
	  File "/usr/local/lib/python3.7/site-packages/cle/backends/elf/elf.py", line 544, in __register_dyn
	    elffile=self.reader, stringtable=self.strtab)
	TypeError: __init__() got an unexpected keyword argument 'stream'

Works fine without it

	>>> p = angr.Project('/bin/ls')
	WARNING | 2019-06-19 00:48:43,194 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.