Fix CONFIGURE_ARGS
- --with-fftw and --without-mpi no longer exist in current configure
- Disable GUI for the moment as there are problems with FLTK:

/usr/ports/pobj/octave-3.8.2/octave-3.8.2/libinterp/dldfcn/__init_fltk__.cc:
In member function 'virtual void fltk_graphics_toolkit::close()':
/usr/ports/pobj/octave-3.8.2/octave-3.8.2/libinterp/dldfcn/__init_fltk__.cc:2075:
error: 'Fremove_input_event_hook' was not declared in this scope

/usr/ports/pobj/octave-3.8.2/octave-3.8.2/libinterp/dldfcn/__init_fltk__.cc:
In function 'octave_value_list F__init_fltk__(const octave_value_list&, int)':
/usr/ports/pobj/octave-3.8.2/octave-3.8.2/libinterp/dldfcn/__init_fltk__.cc:2132:
error: 'Fadd_input_event_hook' was not declared in this scope