Import KMyMoney 4.8.0 update.
Fails to compile with infamous "undefined reference to `vtable for ...`" error.
C++ experts are welcome.

N.B.: It's not a GCC fault: both GCC and Clang produce similar
object files with vtable missing, as objdump says.